### ISSUE TITLE
Solution(code along) already provided

### ISSUE THREAD

**Issue by ErinRRose** [learn-co-curriculum/react-using-callbacks-to-pass-information-lab#39] opened 2021-12-21 16:40 UTC
The code along part is already there, when you begin the lab, there is no code to add.

**Comment by lizbur10** [comment] 2021-12-23 18:50
Hi @ErinRRose ! I took a look and it appears to me that the starter code matches what's shown in the lesson. Can you point me to a specific example?

Thanks again for contributing! 💙

**Comment by ErinRRose** [comment] 2021-12-24 01:05
When I did it, all the code that you were suppose to type for the code
along part was already there, so there was nothing for me to type at all.
Please let me know if that doesn't make sense, Thank you, Erin

**Comment by lizbur10** [comment] 2022-01-06 16:26
Hmm, strange. I've gone back through it again and it still looks right to me. 

A lot of the code *is* provided by design. The first place where there's actually code to be entered as part of the code along is in the Update the Matrix Component section (specifically, by adding state). You might want to double check for that specifically. If it is there in your starter code, is it possible you are looking at the code from the solution branch?

**Comment by lizbur10** [comment] 2022-01-13 16:48
I'm going to go ahead and close this issue. Feel free to reopen it if you don't believe it has been addressed.

Thanks for contributing to the Flatiron School curriculum 💙

**Closed as completed by lizbur10** 2022-01-13 16:48 UTC
Labels: se curriculum
